### PR TITLE
added toggle and button components

### PR DESCRIPTION
**Pull request by Napolite**
What this PR does:

Added Button component. 
Added Toggle component

### CODE REVIEW

**Comment by kingsley-einstein** [comment]
@Napolite please provide a description for your PR.

**Comment by Napolite** [comment]
@kingsley-einstein PR has been updated.

**Review by kingsley-einstein — APPROVED** [review]
Looks good to me.

**Review by humaidhusain98 — COMMENTED** [review]
@Napolite  Please place styled components styles outside of React Component. A  Warning is being  generated saying: "The component styled.button with the id of "sc-bdvvtL" has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component."

**Comment by Napolite** [comment]
@kingsley-einstein @humaidhusain98 changes have been made. Good to merge.

**Review by kingsley-einstein — APPROVED** [review]

**Pull request merged**
